name: basta
image: navikt/basta
replicas:
    min: 1
    max: 1 
    cpuThresholdPercentage: 50
prometheus:
    enabled: true
    path: /metrics
port: 8080
healthcheck:
    liveness:
      initialDelay: 60
      path: rest/internal/isAlive
    readiness:
      initialDelay: 60
      path: rest/internal/isAlive
resources:
    limits:
      cpu: 1500m
      memory: 3072Mi
    requests:
      cpu: 128m
      memory: 1536Mi
fasitResources:
  used:
  - alias: bastaDB
    resourceType: datasource
  - alias: orchestrator_callback_host
    resourceType: baseUrl
  - alias: fasit_rest_api
    resourceType: restservice
  - alias: fasit:resources_v2
    resourceType: restservice
  - alias: fasit:environments_v2
    resourceType: restservice
  - alias: fasit:search_v1
    resourceType: restservice
  - alias: fasit:nodes_v2
    resourceType: restservice
  - alias: fasit:applications_v2
    resourceType: restservice
  - alias: fasit:scopedresource_v2
    resourceType: restservice
  - alias: sensu_api
    resourceType: restservice
  - alias: jira
    resourceType: baseUrl
  - alias: ws_orchestrator
    resourceType: baseUrl
  - alias: rest_orchestrator_provision
    resourceType: baseUrl
  - alias: rest_orchestrator_decomission
    resourceType: baseUrl
  - alias: rest_orchestrator_startstop
    resourceType: baseUrl
  - alias: rest_orchestrator_modify
    resourceType: baseUrl
  - alias: security_CA_adeo
    resourceType: baseUrl
  - alias: security_CA_preprod
    resourceType: baseUrl
  - alias: security_CA_test
    resourceType: baseUrl
  - alias: oem
    resourceType: baseUrl
  - alias: ldap
    resourceType: ldap
  - alias: oem
    resourceType: credential
  - alias: srvbasta
    resourceType: credential
  - alias: user_orchestrator
    resourceType: credential
  - alias: security_CA_adeo
    resourceType: credential
  - alias: security_CA_preprod
    resourceType: credential
  - alias: security_CA_test
    resourceType: credential
  - alias: basta_mq_u
    resourceType: credential
  - alias: basta_mq_t
    resourceType: credential
  - alias: basta_mq_q
    resourceType: credential
  - alias: basta_mq_p
    resourceType: credential
  - alias: basta_operations
    resourceType: roleMapping
  - alias: basta_prodoperations
    resourceType: roleMapping
  - alias: basta_superuser
    resourceType: roleMapping
  - alias: bastaAzureConfig
    resourceType: applicationProperties

webproxy: true
