name: basta
image: docker.adeo.no:5000/basta
replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
port:
  name: http
  port: 80
  targetPort: 8080
  protocol: http
healthcheck:
    liveness:
      path: isAlive
    readiness:
      path: isAlive
fasitResources:
  used:
  - alias: bastaDB
    resourceType: datasource
  - alias: fasit_rest_api
    resourceType: restservice
  - alias: fasit_resources_v2
    resourceType: restservice
  - alias: fasit_environments_v2
    resourceType: restservice
  - alias: fasit_nodes_v2
    resourceType: restservice
  - alias: fasit_applications_v2
    resourceType: restservice
  - alias: fasit_scopedresource_v2
    resourceType: restservice
  - alias: sensu_api
    resourceType: restservice
  - alias: jira
    resourceType: baseUrl
  - alias: ws_orchestrator
    resourceType: baseUrl
  - alias: rest_orchestrator_provision
    resourceType: baseUrl
  - alias: rest_orchestrator_decomission
    resourceType: baseUrl
  - alias: rest_orchestrator_startstop
    resourceType: baseUrl
  - alias: rest_orchestrator_modify
    resourceType: baseUrl
  - alias: security_CA_adeo
    resourceType: baseUrl
  - alias: security_CA_preprod
    resourceType: baseUrl
  - alias: security_CA_test
    resourceType: baseUrl
  - alias: oem
    resourceType: baseUrl
  - alias: ldap
    resourceType: ldap
  - alias: oem
    resourceType: credential
  - alias: srvbasta
    resourceType: credential
  - alias: user_orchestrator
    resourceType: credential
  - alias: security_CA_adeo
    resourceType: credential
  - alias: security_CA_preprod
    resourceType: credential
  - alias: security_CA_test
    resourceType: credential
  - alias: basta_mq_u
    resourceType: credential
  - alias: basta_mq_t
    resourceType: credential
  - alias: basta_mq_q
    resourceType: credential
  - alias: basta_mq_p
    resourceType: credential
  exposed:
  - alias: basta_rest_api
    resourceType: restservice
    path: /rest
  - alias: oracle_v1
    resourceType: restservice
    path: /rest/v1/oracledb
