CREATE SEQUENCE  "HIBERNATE_SEQUENCE";

  CREATE TABLE "NODE" 
   (	"ID" NUMBER(19,0), 
	"CREATED" TIMESTAMP (6), 
	"CREATEDBY" VARCHAR2(255 CHAR), 
	"UPDATED" TIMESTAMP (6), 
	"UPDATEDBY" VARCHAR2(255 CHAR), 
	"ADMINURL" VARCHAR2(255 CHAR), 
	"APPLICATIONSERVERTYPE" VARCHAR2(255 CHAR), 
	"CPUCOUNT" NUMBER(10,0), 
	"DATASENTER" VARCHAR2(255 CHAR), 
	"FASITUPDATED" NUMBER(1,0), 
	"HOSTNAME" VARCHAR2(255 CHAR), 
	"MEMORYMB" NUMBER(10,0), 
	"ORDERID" NUMBER(19,0), 
	"VAPP" VARCHAR2(255 CHAR)
   );

  CREATE TABLE "ORDERTABLE" 
   (	"ID" NUMBER(19,0), 
	"CREATED" TIMESTAMP (6), 
	"CREATEDBY" VARCHAR2(255 CHAR), 
	"UPDATED" TIMESTAMP (6), 
	"UPDATEDBY" VARCHAR2(255 CHAR), 
	"ORCHESTRATORORDERID" VARCHAR2(255 CHAR), 
	"REQUESTXML" CLOB
   );

  CREATE TABLE "SETTINGS" 
   (	"ID" NUMBER(19,0), 
	"CREATED" TIMESTAMP (6), 
	"CREATEDBY" VARCHAR2(255 CHAR), 
	"UPDATED" TIMESTAMP (6), 
	"UPDATEDBY" VARCHAR2(255 CHAR), 
	"APPLICATIONNAME" VARCHAR2(255 CHAR), 
	"APPLICATIONSERVERTYPE" VARCHAR2(255 CHAR), 
	"ENVIRONMENTCLASS" VARCHAR2(255 CHAR), 
	"ENVIRONMENTNAME" VARCHAR2(255 CHAR), 
	"SERVERCOUNT" NUMBER(10,0), 
	"SERVERSIZE" VARCHAR2(255 CHAR), 
	"ZONE" VARCHAR2(255 CHAR), 
	"DISK" NUMBER(1,0), 
	"MULTISITE" NUMBER(1,0), 
	"ORDER_ID" NUMBER(19,0)
   );


  CREATE UNIQUE INDEX "SYS_C005079" ON "NODE" ("ID");

  CREATE UNIQUE INDEX "SYS_C005082" ON "SETTINGS" ("ID");

  CREATE UNIQUE INDEX "SYS_C005084" ON "ORDERTABLE" ("ID");

  ALTER TABLE "NODE" ADD PRIMARY KEY ("ID") USING INDEX;
  ALTER TABLE "NODE" MODIFY ("MEMORYMB" NOT NULL ENABLE);
  ALTER TABLE "NODE" MODIFY ("FASITUPDATED" NOT NULL ENABLE);
  ALTER TABLE "NODE" MODIFY ("CPUCOUNT" NOT NULL ENABLE);
  ALTER TABLE "NODE" MODIFY ("ID" NOT NULL ENABLE);

  ALTER TABLE "ORDERTABLE" ADD PRIMARY KEY ("ID") USING INDEX;
  ALTER TABLE "ORDERTABLE" MODIFY ("ID" NOT NULL ENABLE);

  ALTER TABLE "SETTINGS" ADD PRIMARY KEY ("ID") USING INDEX;
  ALTER TABLE "SETTINGS" MODIFY ("SERVERCOUNT" NOT NULL ENABLE);
  ALTER TABLE "SETTINGS" MODIFY ("ID" NOT NULL ENABLE);

  ALTER TABLE "SETTINGS" ADD CONSTRAINT "FK_AQJ7YX11JTY2EKIJBH51WHBTA" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "ORDERTABLE" ("ID") ENABLE;
