
ALTER TABLE SETTINGS RENAME COLUMN APPLICATIONNAME TO APPLICATIONMAPPINGNAME;

ALTER TABLE SETTINGS ADD (
	MAPPINGTYPE VARCHAR2(255 CHAR)
);

UPDATE SETTINGS
  SET MAPPINGTYPE = 'APPLICATION' where MAPPINGTYPE is NULL;