
ALTER TABLE NODE ADD (

	CREATEDBYDISPLAYNAME VARCHAR2(255 CHAR),
  UPDATEDBYDISPLAYNAME VARCHAR2(255 CHAR)
);

ALTER TABLE ORDERTABLE ADD (

	CREATEDBYDISPLAYNAME VARCHAR2(255 CHAR),
  UPDATEDBYDISPLAYNAME VARCHAR2(255 CHAR)
);

ALTER TABLE SETTINGS ADD (

	CREATEDBYDISPLAYNAME VARCHAR2(255 CHAR),
  UPDATEDBYDISPLAYNAME VARCHAR2(255 CHAR)
);

ALTER TABLE ORDERSTATUSLOG ADD (

	CREATEDBYDISPLAYNAME VARCHAR2(255 CHAR),
  UPDATEDBYDISPLAYNAME VARCHAR2(255 CHAR)
);