
ALTER TABLE ORDERTABLE ADD(
 SETTINGS_ID NUMBER(19,0)
);

UPDATE ORDERTABLE
  SET SETTINGS_ID = (SELECT ID FROM SETTINGS WHERE ORDERTABLE.ID = SETTINGS.ORDER_ID)
  WHERE SETTINGS_ID IS NULL;

ALTER TABLE SETTINGS  DROP COLUMN ORDER_ID;

