CREATE TABLE "ORDERSTATUSLOG"
   (
      "ID" NUMBER(19,0) NOT NULL,
	    "CREATED" TIMESTAMP (6),
	    "CREATEDBY" VARCHAR2(255 CHAR),
	    "UPDATED" TIMESTAMP (6),
	    "UPDATEDBY" VARCHAR2(255 CHAR),
	    "STATUSTEXT" VARCHAR2(255 CHAR),
	    "STATUSTYPE" VARCHAR2(255 CHAR),
	    "STATUSOPTION" VARCHAR2(255 CHAR),
	    "ORDERID" NUMBER(19,0),
      CONSTRAINT pk_orderstatus_id PRIMARY KEY ("ID"),
      CONSTRAINT fk_order_id FOREIGN KEY ("ORDERID") REFERENCES ORDERTABLE("ID")
   );