ALTER TABLE NODE RENAME COLUMN APPLICATIONSERVERTYPE to MIDDLEWARETYPE;
ALTER TABLE SETTINGS RENAME COLUMN APPLICATIONSERVERTYPE to MIDDLEWARETYPE;

CREATE TABLE SETTINGS_PROPERTIES (
	SETTINGS_ID NUMBER(19,0) NOT NULL,
	PROPERTY_KEY VARCHAR2(255) NOT NULL,
	PROPERTY_VALUE VARCHAR2(255)
);