
CREATE TABLE SYSTEM_NOTIFICATION
   (
      ID NUMBER(19,0) NOT NULL,
	    CREATED TIMESTAMP (6),
	    CREATEDBY VARCHAR2(255 CHAR),
	    UPDATED TIMESTAMP (6),
	    UPDATEDBY VARCHAR2(255 CHAR),
	    ACTIVE NUMBER(1,0),
	    MESSAGE VARCHAR2(4000 CHAR),
      BLOCKOPERATIONS NUMBER(1,0),
      CREATEDBYDISPLAYNAME VARCHAR2(255 CHAR),
      UPDATEDBYDISPLAYNAME VARCHAR2(255 CHAR),
      CONSTRAINT PK_SYSTEM_NOTIFICATION_ID PRIMARY KEY (ID)
   );
