DROP SEQUENCE orderstatus_seq;
CREATE SEQUENCE orderstatus_seq
  START WITH 4000
  INCREMENT BY 1
  CACHE 2;

DROP SEQUENCE order_seq;
CREATE SEQUENCE order_seq
 START WITH 4000
 INCREMENT BY 1
 CACHE 2;
