ALTER TABLE ORDERTABLE ADD (
	STATUS			VARCHAR(255),
	ERRORMESSAGE	VARCHAR(255),
	NODETYPE		VARCHAR(255)
);

UPDATE ORDERTABLE
SET STATUS = 'NEW'
WHERE STATUS IS NULL;

UPDATE ORDERTABLE
SET NODETYPE = (SELECT NODETYPE FROM SETTINGS WHERE ORDERTABLE.ID = SETTINGS.ORDER_ID);

ALTER TABLE ORDERTABLE MODIFY(NODETYPE NOT NULL);
