
ALTER TABLE ORDERTABLE
RENAME COLUMN ORDERTYPE TO ORDEROPERATION;

UPDATE ORDERTABLE
SET ORDEROPERATION = 'CREATE'
WHERE ORDEROPERATION = 'PROVISION';

UPDATE ORDERTABLE
SET ORDEROPERATION = 'DELETE'
WHERE ORDEROPERATION = 'DECOMMISSION';

