UPDATE INPUT_PROPERTIES
SET INPUT_VALUE = 'JBOSS'
WHERE INPUT_VALUE = 'APPLICATION_SERVER' AND INPUT_KEY = 'nodeType';



UPDATE RESULT_PROPERTIES
SET RESULT_VALUE = 'JBOSS'
WHERE RESULT_VALUE = 'APPLICATION_SERVER';


