module.exports = function($routeProvider){
    $routeProvider.when('/serviceuser_certificate_order',   { templateUrl: 'basta/orderform/serviceuser/serviceuser_certificate_order_form.html'});
    $routeProvider.when('/serviceuser_credential_order',    { templateUrl: 'basta/orderform/serviceuser/serviceuser-credential-order_form.html'});
    $routeProvider.when('/vm_order',                        { templateUrl: 'basta/orderform/websphere/order_form_vm.html'});
    $routeProvider.when('/jboss_order',                     { templateUrl: 'basta/orderform/jboss/jboss-orderform.html'});
    $routeProvider.when('/wildfly_order',                   { templateUrl: 'basta/orderform/wildfly/wildfly-orderform.html'});
    $routeProvider.when('/openam_server_order',             { templateUrl: 'basta/orderform/openam/openam-server-orderform.html'});
    $routeProvider.when('/openam_proxy_order',              { templateUrl: 'basta/orderform/openam/openam-proxy-orderform.html'});
    $routeProvider.when('/linux_order',                     { templateUrl: 'basta/orderform/linux/linux-orderform.html'});
    $routeProvider.when('/windows_order',                   { templateUrl: 'basta/orderform/windows/windows-orderform.html'});
    $routeProvider.when('/was_node_order',                  { templateUrl: 'basta/orderform/websphere/was-node-orderform.html'});
    $routeProvider.when('/was_dmgr_order',                  { templateUrl: 'basta/orderform/websphere/was-dmgr-orderform.html'});
    $routeProvider.when('/bpm_node_order',                  { templateUrl: 'basta/orderform/bpm/bpm-node-orderform.html'});
    $routeProvider.when('/bpm_dmgr_order',                  { templateUrl: 'basta/orderform/bpm/bpm-dmgr-orderform.html'});
    $routeProvider.when('/oracle_order',                    { templateUrl: 'basta/orderform/oracle/oracle-orderform.html'});
    $routeProvider.when('/mq_queue_order',    				{ templateUrl: 'basta/orderform/mq/mq-queue-orderform.html'});
    $routeProvider.when('/menu',                            { templateUrl: 'basta/order-menu/order-menu.html'});
    $routeProvider.when('/operation_menu',                  { templateUrl: 'basta/order-menu/operation-menu.html'});
    $routeProvider.when('/operations_node',                 { templateUrl: 'basta/order-operation/vm/vm-operations.html'});
    $routeProvider.when('/operations_credential',           { templateUrl: 'basta/order-operation/serviceuser/serviceuser-operations.html'});
    $routeProvider.when('/notifications',                   { templateUrl: 'basta/notifications/notifications.html'});
    $routeProvider.when('/order_list',                      { templateUrl: 'basta/orderlist/order_list.html'});
    $routeProvider.when('/order_details/:id',               { templateUrl: 'basta/orderdetails/order_details.html'});
    $routeProvider.when('/changelog',                       { templateUrl: 'basta/changelog/changelog.html'});
    $routeProvider.otherwise(                               { redirectTo: '/order_list'});
};