package no.nav.aura.basta.backend.vmware.orchestrator;

public enum MiddlewareType {
    was,
    was_9,
    jboss,
    linux,
    devtools,
    containerlinux,
    flatcarlinux,
    bpm, 
    bpm_86,
    wa, 
    jb, 
    ap, 
    jboss_eap_6, 
    jboss_eap_7, 
    liberty_16,
    openam_server_12,
    openam_proxy_12,
    openam_server_13,
    openam_proxy_13,
    wildfly_11,
    wildfly_17,
    wildfly_19,
    wildfly_21,
    wildfly_23,
    wildfly_25,
    wildfly_27,
    wildfly_29,
    windows_ap,
    windows_is,
}
