package no.nav.aura.basta.backend.vmware.orchestrator;

public enum MiddlewareType {
    was,
    was_9,
    jboss,
    linux,
    devtools,
    containerlinux,
    flatcarlinux,
    bpm, 
    bpm_86,
    wa, 
    jb, 
    jboss_eap_7,
    wildfly_11,
    wildfly_17,
    wildfly_19,
    wildfly_21,
    wildfly_23,
    wildfly_25,
    wildfly_27,
    wildfly_29,
    windows_ap,
}
