
package no.nav.vmware.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VSOWebControlService", targetNamespace = "http://webservice.vso.dunes.ch", wsdlLocation = "./vmware.wsdl")
public class VSOWebControlService
    extends Service
{

    private final static URL VSOWEBCONTROLSERVICE_WSDL_LOCATION;
    private final static WebServiceException VSOWEBCONTROLSERVICE_EXCEPTION;
    private final static QName VSOWEBCONTROLSERVICE_QNAME = new QName("http://webservice.vso.dunes.ch", "VSOWebControlService");

    static {
        URL url = null;
        WebServiceException e = null;
//        try {
//            url = new URL("file:/C:/Users/V137023/AppData/Local/Temp/tempdir4166845921795970463.tmp/webservice_1.wsdl");
//        } catch (MalformedURLException ex) {
//            e = new WebServiceException(ex);
//        }
        VSOWEBCONTROLSERVICE_WSDL_LOCATION = url;
        VSOWEBCONTROLSERVICE_EXCEPTION = e;
    }

    public VSOWebControlService() {
        super(__getWsdlLocation(), VSOWEBCONTROLSERVICE_QNAME);
    }

    public VSOWebControlService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VSOWEBCONTROLSERVICE_QNAME, features);
    }

    public VSOWebControlService(URL wsdlLocation) {
        super(wsdlLocation, VSOWEBCONTROLSERVICE_QNAME);
    }

    public VSOWebControlService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VSOWEBCONTROLSERVICE_QNAME, features);
    }

    public VSOWebControlService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VSOWebControlService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VSOWebControl
     */
    @WebEndpoint(name = "webservice")
    public VSOWebControl getWebservice() {
        return super.getPort(new QName("http://webservice.vso.dunes.ch", "webservice"), VSOWebControl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VSOWebControl
     */
    @WebEndpoint(name = "webservice")
    public VSOWebControl getWebservice(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.vso.dunes.ch", "webservice"), VSOWebControl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VSOWEBCONTROLSERVICE_EXCEPTION!= null) {
            throw VSOWEBCONTROLSERVICE_EXCEPTION;
        }
        return VSOWEBCONTROLSERVICE_WSDL_LOCATION;
    }

}
