name: Build and deploy basta

on:
  push:
    branches:
      - master

env:
  IMAGE: ghcr.io/${{ github.repository }}/basta:${{ github.sha }}

jobs:
  build:
    name: Build and push Docker image
    runs-on: basta-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache Maven dependencies
        uses: actions/cache@preview
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name:
        uses: actions/setup-java@v1
        with:
          java-version: '8.0.x'

      - name: Build java backend
        run: mvn install

      - name: Build docker image
        run: docker build --tag ${IMAGE} .
      - name: Login to Github package registry
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_PUSH_TOKEN }}
        run : docker login ghcr.io -u ${{ GHCR_PUSH_USERNAME}} -p ${GITHUB_TOKEN}
      - name: Push docker image
        run: docker push ${IMAGE}

      - name: Deploy to dev-fss
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: nais/naiserator.yml
          VARS: nais/dev-config.json

          #- name: Deploy to prod-fss
          #uses: nais/deploy/actions/deploy@v1
          #env:
          #APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          #CLUSTER: prod-fss
          #RESOURCE: nais/naiserator.yml
          #VARS: nais/prod-config.json
