name: Build and deploy basta

on:
  push:
    branches:
      - master

env:
  IMAGE: ghcr.io/${{ github.repository }}/basta:${{ github.sha }}

jobs:
  build:
    name: Build and push Docker image
    runs-on: basta-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cache Maven dependencies
        uses: actions/cache@preview
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'maven'
          check-latest: true

      - name: Build java backend
        run: mvn -s ~/.m2/localsettings.xml -DskipTests=true install 

      - name: Build docker image
        run: docker build --tag ${IMAGE} .

      - name: Login to Github package registry
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_PUSH_TOKEN }}
        run : echo ${GHCR_TOKEN} | docker login ghcr.io -u ${{ secrets.GHCR_PUSH_USERNAME}} --password-stdin
      - name: Push docker image
        run: docker push ${IMAGE}

      - name: Deploy to dev-fss
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: .nais/naiserator-dev.yml
          VARS: .nais/basta-dev-fss.json
           
          #- name: Deploy to prod-fss
          #uses: nais/deploy/actions/deploy@v1
          #env:
          #APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          #CLUSTER: prod-fss
          #RESOURCE: nais/naiserator.yml
          #VARS: nais/prod-config.json
