name: Build and deploy basta

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.github/workflows/pr.yaml'
      - '.github/dependabot.yml'

env:
  IMAGE: ghcr.io/${{ github.repository }}/basta:${{ github.sha }}

jobs:
  build:
    name: Build and push Docker image
    runs-on: basta-runner
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'maven'
          check-latest: true

      #- name: Test java backend
      #  run: mvn -s ~/.m2/localsettings.xml test

      - name: Build java backend
        run: mvn -s ~/.m2/localsettings.xml -DskipTests=true install

      - name: Change permissions for shell scripts
        run: chmod +x .nais/*.sh target/basta*.war

      - name: Login to Github package registry
        run : echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository }} --password-stdin

      - name: Build docker image
        run: docker build --tag ${IMAGE} .

      - name: Push docker image
        run: docker push ${IMAGE}

      - name: Retrieve Image Digest (SHA-256)
        id: digest
        run: |
          DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' "$IMAGE" | awk -F@ '{print $2}')
          echo "Digest: $DIGEST"
          
          # Output the digest for later steps
          echo "::set-output name=sha256::$DIGEST"

      - name: Attest and sign image
        uses: nais/attest-sign@v1
        id: attest-sign
        with:
          image_ref: ghcr.io/${{ github.repository }}/basta@${{ steps.digest.outputs.sha256 }}

          #      - uses: nais/docker-build-push@v0
          #        id: build-push-sign
          #        with:
          #          team: team-atom
          #          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          #          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

      - name: Deploy to dev-fss
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-fss
          RESOURCE: .nais/naiserator-dev.yml
          VARS: .nais/basta-dev-fss.json

      - name: Deploy to prod-fss
        uses: nais/deploy/actions/deploy@v2
        if: github.ref == 'refs/heads/main'
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: .nais/naiserator.yml
          VARS: .nais/basta-prod-fss.json
