name: Build and deploy basta

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.github/workflows/pr.yaml'
      - '.github/dependabot.yml'
  workflow_dispatch:

env:
    TEAM: team-atom

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'maven'
          check-latest: true

      #- name: Test java backend
      #  run: mvn test

      - name: Build java backend
        run: mvn -DskipTests=true install

      - name: Change permissions for shell scripts
        run: chmod +x .nais/*.sh target/basta*.war

      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: team-atom

      - name: Deploy to dev-fss
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-fss
          RESOURCE: .nais/naiserator-dev.yml
          VARS: .nais/basta-dev-fss.json
          IMAGE: "${{ steps.docker-push.outputs.image }}"

      - name: Deploy to prod-fss
        uses: nais/deploy/actions/deploy@v2
        if: github.ref == 'refs/heads/main'
        env:
          CLUSTER: prod-fss
          RESOURCE: .nais/naiserator.yml
          VARS: .nais/basta-prod-fss.json
          IMAGE: "${{ steps.docker-push.outputs.image }}"
