name: Run integration tests when pull request is created

on:
  pull_request:
    types: 
      - opened
      - synchronized
      - reopened
    branches:
      - main

jobs:
  build:
    name: Run integration tests
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'maven'
          check-latest: true

      - name: Test java backend
        run: mvn test

      - name: Build java backend
        run: mvn -DskipTests=true install
